name: config-patcher
version: 1.46.1
commit_hash: 91a9350
uncommitted_changes: false
jobs:
- name: config-patcher
  version: 66aed1bc82e1515983a5ec2bb2fbcce3bc87ef41875ec4ae88be04f90abd2671
  fingerprint: 66aed1bc82e1515983a5ec2bb2fbcce3bc87ef41875ec4ae88be04f90abd2671
  sha1: sha256:cbcc44e21020eff291c073368f262d1c2ddfbb5f3457525f90d0c9c63802e964
  packages:
  - config-patcher
packages:
- name: config-patcher
  version: 09000ebeec2cfa96fd5296d8185ceeb3b2a2c4acfed1b3d8d79b02f9c48df8f0
  fingerprint: 09000ebeec2cfa96fd5296d8185ceeb3b2a2c4acfed1b3d8d79b02f9c48df8f0
  sha1: sha256:7ed056dcaaa919689be683c103fb6cf2fa90a89e5c86d85f3281aeb5678d4ea2
  dependencies: []
license:
  version: 483b12760736e6239e71b4f5d8409f05eb635659e20bba3fa4012ac27347c6c4
  fingerprint: 483b12760736e6239e71b4f5d8409f05eb635659e20bba3fa4012ac27347c6c4
  sha1: sha256:c58d6c1b3e72a4fede10c2cc833ce17600add266b7af83db8194215bc95fa80a
