name: config-patcher
version: 1.47.0
commit_hash: 2390ce9
uncommitted_changes: false
jobs:
- name: config-patcher
  version: 66aed1bc82e1515983a5ec2bb2fbcce3bc87ef41875ec4ae88be04f90abd2671
  fingerprint: 66aed1bc82e1515983a5ec2bb2fbcce3bc87ef41875ec4ae88be04f90abd2671
  sha1: sha256:cbcc44e21020eff291c073368f262d1c2ddfbb5f3457525f90d0c9c63802e964
  packages:
  - config-patcher
packages:
- name: config-patcher
  version: 7e217bdaf5256b7c6a47d0a516a711bc48e6a6d3dde57eff48a77db42f1b454b
  fingerprint: 7e217bdaf5256b7c6a47d0a516a711bc48e6a6d3dde57eff48a77db42f1b454b
  sha1: sha256:4763e26fb9628fe501ed81e3feb51f3215643aad75074d8767091c877016719c
  dependencies: []
license:
  version: 483b12760736e6239e71b4f5d8409f05eb635659e20bba3fa4012ac27347c6c4
  fingerprint: 483b12760736e6239e71b4f5d8409f05eb635659e20bba3fa4012ac27347c6c4
  sha1: sha256:c58d6c1b3e72a4fede10c2cc833ce17600add266b7af83db8194215bc95fa80a
