name: config-patcher
version: 1.46.3
commit_hash: 8dbbb6c
uncommitted_changes: false
jobs:
- name: config-patcher
  version: 66aed1bc82e1515983a5ec2bb2fbcce3bc87ef41875ec4ae88be04f90abd2671
  fingerprint: 66aed1bc82e1515983a5ec2bb2fbcce3bc87ef41875ec4ae88be04f90abd2671
  sha1: sha256:cbcc44e21020eff291c073368f262d1c2ddfbb5f3457525f90d0c9c63802e964
  packages:
  - config-patcher
packages:
- name: config-patcher
  version: c0258aee25c92012bb8f05c02f515131f6b3e81b28f102108207e6fc43ad8b6e
  fingerprint: c0258aee25c92012bb8f05c02f515131f6b3e81b28f102108207e6fc43ad8b6e
  sha1: sha256:10d1c03984d031b29fe10c7a396d26977aed28ed491e461f860ec3bd00b22344
  dependencies: []
license:
  version: 483b12760736e6239e71b4f5d8409f05eb635659e20bba3fa4012ac27347c6c4
  fingerprint: 483b12760736e6239e71b4f5d8409f05eb635659e20bba3fa4012ac27347c6c4
  sha1: sha256:c58d6c1b3e72a4fede10c2cc833ce17600add266b7af83db8194215bc95fa80a
